### PR TITLE
Fix: upgrade ginkgo to v2

### LINKED ISSUE #125: Some tasks still use ginkgo v1 CLI

### PR DESCRIPTION
**Pull request by ctlong**
Closes #125

### CODE REVIEW

File: task-libs/bosh/manifest_test.go [hunk 1]
```diff
@@ -103,18 +103,18 @@ update:
...
+      sha1: ""
+      url: ""
+      version: ""
 stemcells:
-  - alias: default
-    os: some-os
-    version: 1.2.3
+    - alias: default
+      os: some-os
+      version: 1.2.3
```
Comment (davewalter) [inline task-libs/bosh/manifest_test.go:117]: Is this valid YAML with this level of indentation?

**Review by davewalter — COMMENTED** [review]
Looks good overall. I just had one question about inline YAML manifest.

File: task-libs/bosh/manifest_test.go (hunk 1 above)
Comment (ctlong) [reply task-libs/bosh/manifest_test.go:117]: I've no idea if it's valid yaml, but it fixes the tests, which have been failing for some time as far as I can tell.

**Review by davewalter — APPROVED** [review]
